services:
    postgresDB:
        image: postgres:17-alpine
        hostname: "db"
        restart: "always"
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
        ports:
            - "5432:5432"
        volumes:
            - postgresDB:/var/lib/postgresql/data

volumes:
    postgresDB:
